### ISSUE TITLE
requirements.txt missing python-opencv

### ISSUE THREAD

**Issue by davidrhodus** [HackerShackOfficial/Smart-Security-Camera#2]
pi@drpi:~/Smart-Security-Camera $ python main.py 
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import cv2
ImportError: No module named cv2
pi@drpi:~/Smart-Security-Camera $ cat requirements.txt 
imutils
flask
picamera[array]

**Comment by the04dude** [comment]
I am experiencing this issue as well.  I'm new to Python...  Can I fix this by adding something to the requirements file?

**Comment by debsahu** [comment]
You have manually compile and install opencv as per instructions in readme. Use this link: http://www.pyimagesearch.com/2016/04/18/install-guide-raspberry-pi-3-raspbian-jessie-opencv-3/
